[package]
name = "testing"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
libp2p = { version = "0.56.0", features = ["kad", "macros"] }
libp2p-invert = { path = "../libp2p-invert"}
tokio = { version = "1.47.1", features = ["sync", "macros"] }
