[package]
name = "libp2p-invert"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
syn = { version = "2.0", features = ["full", "visit-mut"] }
quote = "1.0"
heck = "0.5.0"
syn_derive = "0.2.0"
